### ISSUE TITLE
flaky compiler crashes

### ISSUE THREAD

**Issue by radkomih** [LimeChain/gosemble#197]
Sometimes, after making a code change, compilation fails randomly and with different traces. However, if we wait long enough before trying again, it often succeeds.

```sh
panic: runtime error: index out of range [0] with length 0

goroutine 179 [running]:
github.com/tinygo-org/tinygo/compiler.(*builder).createFunctionStart(0x1400588e900, 0x0)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1219 +0xe90
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0x1400588e900)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1308 +0x2c
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getFunction(0x14007f60140, 0x14007924000)
	/Users/USER/Dev/gosemble/tinygo/compiler/symbol.go:224 +0xc08
github.com/tinygo-org/tinygo/compiler.(*builder).getValue(0x1400588e780, {0x1010552d0?, 0x14007924000?}, 0x0?)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1964 +0x28c
github.com/tinygo-org/tinygo/compiler.(*builder).createFunctionCall(0x1400588e780, 0x14009d5fec0)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1847 +0xc8
github.com/tinygo-org/tinygo/compiler.(*builder).createExpr(0x1400588e780, {0x101055630, 0x14009d5fe80})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:2047 +0x3f4
github.com/tinygo-org/tinygo/compiler.(*builder).createInstruction(0x1400588e780, {0x101055510?, 0x14009d5fe80?})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1460 +0x820
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0x1400588e780)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1349 +0x854
github.com/tinygo-org/tinygo/compiler.(*compilerContext).createPackage(0x14007f60140, {0x14005577680?}, 0x14005732980)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:901 +0x730
github.com/tinygo-org/tinygo/compiler.CompilePackage({0x14000247e60?, 0x66?}, 0x14000251a40, 0x14005732980, {0x1a7fc6ee6248ae82?}, 0x100f0ccc5?, 0x18?)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:312 +0x3a8
github.com/tinygo-org/tinygo/builder.Build.func3(0x14005792c00)
	/Users/USER/Dev/gosemble/tinygo/builder/build.go:365 +0x18c
github.com/tinygo-org/tinygo/builder.runJob(0x14005792c00, 0x0?)
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:222 +0x48
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:123 +0x434
make: *** [build-release] Error 2
```

```sh
panic: runtime error: index out of range [0] with length 0

goroutine 92 [running]:
github.com/tinygo-org/tinygo/compiler.(*builder).createFunctionStart(0x14007b60600, 0x0)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1219 +0xe90
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0x14007b60600)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1308 +0x2c
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getFunction(0x14004e9a8c0, 0x1400716e900)
	/Users/USER/Dev/gosemble/tinygo/compiler/symbol.go:224 +0xc08
github.com/tinygo-org/tinygo/compiler.(*builder).createFunctionCall(0x14007b60480, 0x140025d7840)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1883 +0x848
github.com/tinygo-org/tinygo/compiler.(*builder).createExpr(0x14007b60480, {0x1028b9630, 0x140025d7800})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:2047 +0x3f4
github.com/tinygo-org/tinygo/compiler.(*builder).createInstruction(0x14007b60480, {0x1028b9510?, 0x140025d7800?})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1460 +0x820
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0x14007b60480)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1349 +0x854
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getFunction(0x14004e9a8c0, 0x1400716ec00)
	/Users/USER/Dev/gosemble/tinygo/compiler/symbol.go:224 +0xc08
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeMethodSet(0x14004e9a8c0, {0x1028b6598, 0x1400534b1a0})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:617 +0x1d4
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6598, 0x1400534b1a0?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:415 +0x2b78
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6458, 0x1400018b880?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:290 +0x2260
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6570, 0x14003138780?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:392 +0x3270
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6458, 0x140001a0460?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:291 +0x227c
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6548, 0x14004d25870?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:316 +0x24bc
github.com/tinygo-org/tinygo/compiler.(*compilerContext).getTypeCode(0x14004e9a8c0, {0x1028b6458, 0x14004cf6a80?})
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:291 +0x227c
github.com/tinygo-org/tinygo/compiler.(*builder).createMakeInterface(0x14006c98000, {0x1028b9af8?}, {0x1028b6458, 0x14004cf6a80}, 0x14006e82f58?)
	/Users/USER/Dev/gosemble/tinygo/compiler/interface.go:80 +0x6c
github.com/tinygo-org/tinygo/compiler.(*builder).createExpr(0x14006c98000, {0x1028b93f0, 0x140058c2320})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:2235 +0x139c
github.com/tinygo-org/tinygo/compiler.(*builder).createInstruction(0x14006c98000, {0x1028ba488?, 0x140058c2320?})
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1460 +0x820
github.com/tinygo-org/tinygo/compiler.(*builder).createFunction(0x14006c98000)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:1349 +0x854
github.com/tinygo-org/tinygo/compiler.(*compilerContext).createPackage(0x14004e9a8c0, {0x14005623680?}, 0x140057e4980)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:901 +0x730
github.com/tinygo-org/tinygo/compiler.CompilePackage({0x1400015be60?, 0x66?}, 0x14000165a40, 0x140057e4980, {0xeb452df43145fe8?}, 0x102770cc5?, 0x18?)
	/Users/USER/Dev/gosemble/tinygo/compiler/compiler.go:312 +0x3a8
github.com/tinygo-org/tinygo/builder.Build.func3(0x14005840ba0)
	/Users/USER/Dev/gosemble/tinygo/builder/build.go:365 +0x18c
github.com/tinygo-org/tinygo/builder.runJob(0x14005840ba0, 0x0?)
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:222 +0x48
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:123 +0x434
make: *** [build-release] Error 2
```

```sh
tinygo(51223,0x17b547000) malloc: *** error for object 0x600001547450: pointer being freed was not allocated
tinygo(51223,0x17b547000) malloc: *** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x186b5c764 m=5 sigcode=0
signal arrived during cgo execution

goroutine 239 [syscall]:
runtime.cgocall(0x104c42600, 0x1400669daf8)
	/usr/local/go/src/runtime/cgocall.go:157 +0x44 fp=0x1400669dac0 sp=0x1400669da80 pc=0x1048defa4
tinygo.org/x/go-llvm._Cfunc_LLVMDisposeModule(0x12e016510)
	_cgo_gotypes.go:4678 +0x30 fp=0x1400669daf0 sp=0x1400669dac0 pc=0x104af1bc0
tinygo.org/x/go-llvm.Module.Dispose.func1({0x1400669dba8?})
	/Users/USER/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20221028183034-8341240c0b32/ir.go:464 +0x50 fp=0x1400669db30 sp=0x1400669daf0 pc=0x104afcc20
tinygo.org/x/go-llvm.Module.Dispose({0x140057680e0?})
	/Users/USER/go/pkg/mod/tinygo.org/x/go-llvm@v0.0.0-20221028183034-8341240c0b32/ir.go:464 +0x1c fp=0x1400669db50 sp=0x1400669db30 pc=0x104afcbac
github.com/tinygo-org/tinygo/builder.Build.func3.7()
	/Users/USER/Dev/gosemble/tinygo/builder/build.go:367 +0x28 fp=0x1400669db70 sp=0x1400669db50 pc=0x104c10848
runtime.deferreturn()
	/usr/local/go/src/runtime/panic.go:477 +0x38 fp=0x1400669dbb0 sp=0x1400669db70 pc=0x10490e6f8
github.com/tinygo-org/tinygo/builder.Build.func3(0x1400573b860)
	/Users/USER/Dev/gosemble/tinygo/builder/build.go:485 +0xb18 fp=0x1400669df60 sp=0x1400669dbb0 pc=0x104c104b8
github.com/tinygo-org/tinygo/builder.runJob(0x1400573b860, 0x0?)
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:222 +0x48 fp=0x1400669dfb0 sp=0x1400669df60 pc=0x104c1b5e8
github.com/tinygo-org/tinygo/builder.runJobs.func2()
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:123 +0x2c fp=0x1400669dfd0 sp=0x1400669dfb0 pc=0x104c1afcc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400669dfd0 sp=0x1400669dfd0 pc=0x1049436b4
created by github.com/tinygo-org/tinygo/builder.runJobs in goroutine 1
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:123 +0x434

goroutine 1 [chan receive]:
runtime.gopark(0x140057a22a0?, 0x1048e7e2c?, 0x60?, 0x18?, 0x18?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14001d4a510 sp=0x14001d4a4f0 pc=0x104912618
runtime.chanrecv(0x140053e9320, 0x14001d4a6d0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x414 fp=0x14001d4a590 sp=0x14001d4a510 pc=0x1048e12d4
runtime.chanrecv1(0x104d2aca0?, 0x14005760330?)
	/usr/local/go/src/runtime/chan.go:442 +0x14 fp=0x14001d4a5c0 sp=0x14001d4a590 pc=0x1048e0e84
github.com/tinygo-org/tinygo/builder.runJobs(0x140056759b0?, 0x104c55c17?)
	/Users/USER/Dev/gosemble/tinygo/builder/jobs.go:132 +0x450 fp=0x14001d4a9c0 sp=0x14001d4a5c0 pc=0x104c1ac90
github.com/tinygo-org/tinygo/builder.Build({0x16b5274a0, 0x12}, {0x16b52748d, 0x12}, {0x140002061e0, 0x41}, 0x1400015c5a0)
	/Users/USER/Dev/gosemble/tinygo/builder/build.go:885 +0x306c fp=0x14001d4b510 sp=0x14001d4a9c0 pc=0x104c0b32c
main.Build({0x16b5274a0, 0x12}, {0x16b52748d, 0x12}, 0x14000200000)
	/Users/USER/Dev/gosemble/tinygo/main.go:169 +0x194 fp=0x14001d4b730 sp=0x14001d4b510 pc=0x104c2f2d4
main.main()
	/Users/USER/Dev/gosemble/tinygo/main.go:1592 +0x2fc8 fp=0x14001d4bf30 sp=0x14001d4b730 pc=0x104c3b128
runtime.main()
	/usr/local/go/src/runtime/proc.go:267 +0x2bc fp=0x14001d4bfd0 sp=0x14001d4bf30 pc=0x1049121ec
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14001d4bfd0 sp=0x14001d4bfd0 pc=0x1049436b4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000056f90 sp=0x14000056f70 pc=0x104912618
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:322 +0xb8 fp=0x14000056fd0 sp=0x14000056f90 pc=0x1049124a8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000056fd0 sp=0x14000056fd0 pc=0x1049436b4
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000057760 sp=0x14000057740 pc=0x104912618
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:321 +0x108 fp=0x140000577b0 sp=0x14000057760 pc=0x1048ff3b8
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:200 +0x28 fp=0x140000577d0 sp=0x140000577b0 pc=0x1048f40a8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000577d0 sp=0x140000577d0 pc=0x1049436b4
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x14000080000?, 0x104cddf38?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000057f50 sp=0x14000057f30 pc=0x104912618
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x104ffcd00)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x5c fp=0x14000057f80 sp=0x14000057f50 pc=0x1048fcbbc
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0xac fp=0x14000057fb0 sp=0x14000057f80 pc=0x1048fd17c
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:201 +0x28 fp=0x14000057fd0 sp=0x14000057fb0 pc=0x1048f4048
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000057fd0 sp=0x14000057fd0 pc=0x1049436b4
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:201 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x0?, 0x104d8f1b0?, 0x0?, 0xe0?, 0x2000000020?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000056580 sp=0x14000056560 pc=0x104912618
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x108 fp=0x140000567d0 sp=0x14000056580 pc=0x1048f3198
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000567d0 sp=0x140000567d0 pc=0x1049436b4
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:163 +0x80

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x96e7f2a1aa34?, 0x1?, 0x4e?, 0x8c?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400028e730 sp=0x1400028e710 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x1400028e7d0 sp=0x1400028e730 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400028e7d0 sp=0x1400028e7d0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 50 [GC worker (idle)]:
runtime.gopark(0x96e7f9a3ae99?, 0x3?, 0x50?, 0xbc?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000052f30 sp=0x14000052f10 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x14000052fd0 sp=0x14000052f30 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000052fd0 sp=0x14000052fd0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x96e7e896b8bf?, 0x3?, 0x16?, 0xd7?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000053730 sp=0x14000053710 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x140000537d0 sp=0x14000053730 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140000537d0 sp=0x140000537d0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 51 [GC worker (idle)]:
runtime.gopark(0x96e7f9a3b56f?, 0x3?, 0x1d?, 0xe?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400028a730 sp=0x1400028a710 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x1400028a7d0 sp=0x1400028a730 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400028a7d0 sp=0x1400028a7d0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 52 [GC worker (idle)]:
runtime.gopark(0x96e7f98e03b9?, 0x3?, 0xa0?, 0xfd?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400028af30 sp=0x1400028af10 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x1400028afd0 sp=0x1400028af30 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400028afd0 sp=0x1400028afd0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x96e7f9a3def0?, 0x1?, 0xae?, 0x46?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400028ef30 sp=0x1400028ef10 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x1400028efd0 sp=0x1400028ef30 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400028efd0 sp=0x1400028efd0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x96e7f9a3b257?, 0x1?, 0xaa?, 0x1f?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x14000053f30 sp=0x14000053f10 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x14000053fd0 sp=0x14000053f30 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000053fd0 sp=0x14000053fd0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

goroutine 53 [GC worker (idle)]:
runtime.gopark(0x96e7f9a3b0b6?, 0x3?, 0x77?, 0xb4?, 0x0?)
	/usr/local/go/src/runtime/proc.go:398 +0xc8 fp=0x1400028b730 sp=0x1400028b710 pc=0x104912618
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1293 +0xd8 fp=0x1400028b7d0 sp=0x1400028b730 pc=0x1048f5a68
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400028b7d0 sp=0x1400028b7d0 pc=0x1049436b4
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1217 +0x28

r0      0x0
r1      0x0
r2      0x0
r3      0x0
r4      0x73
r5      0x2e
r6      0x1
r7      0x1
r8      0x46210402423b8ecc
r9      0x46210403396ffecc
r10     0xcccccccccccccccd
r11     0xa
r12     0x0
r13     0x35
r14     0x16826ffd
r15     0x16626027
r16     0x148
r17     0x1e673b3a0
r18     0x0
r19     0x6
r20     0x17b547000
r21     0xb03
r22     0x17b5470e0
r23     0x17b546e00
r24     0x0
r25     0x0
r26     0x16b527459
r27     0x17b547000
r28     0x140001021a0
r29     0x17b546750
lr      0x186b93c28
sp      0x17b546730
pc      0x186b5c764
fault   0x186b5c764
make: *** [build-release] Error 2
```

**Comment by failfmi** [comment]
Closing this as it is resolved with update of TinyGo to 0.30, included in #200. We will open a new issue in case in occurs again.
